version: '3'

services:
  redis:
    container_name: 'homeland_redis'
    image: redis:7-alpine
    ports:
      - '6379'
    volumes:
      - ./data/redis:/data
      - ./etc/redis.conf:/etc/redis.conf
    command: redis-server /etc/redis.conf

  app: &app_base
    container_name: 'homeland_app'
    image: homeland/homeland:v3.10.0
    env_file:
      - app.secret.env
      - app.local.env
    links:
      - redis
    logging:
      options:
        max-size: '1g'
        max-file: '10'
    volumes:
      - ./data/uploads:/home/app/homeland/public/uploads
      - ./shared/cache/uploads-thumb:/home/app/cache/uploads-thumb
      - ./shared/plugins:/home/app/homeland/plugins
      - ./log:/home/app/log
      - ./tmp/pids:/home/app/pids
      - ./log:/home/app/homeland/log
      - ./tmp:/home/app/homeland/tmp
      - ./etc/nginx/conf.d:/etc/nginx/conf.d
    command: /home/app/homeland/bin/docker-start
    ports:
      - '7000'

  app_backup:
    <<: *app_base
    container_name: 'homeland_app_backup'
    command: bundle exec puma -C config/puma-backup.rb
    ports:
      - '7001'

  worker:
    <<: *app_base
    container_name: 'homeland_worker'
    ports: []
    command: bundle exec sidekiq -C config/sidekiq.yml

  web:
    <<: *app_base
    container_name: 'homeland_web'
    links:
      - app
      - app_backup
      - worker
    command: /etc/nginx/start
    ports:
      - '8080:80'

